---

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: escuela
      MYSQL_DATABASE: escuela
    command: ['--wait-timeout=1500000']
networks:
  db:
    internal: true
